### ISSUE TITLE
Need more collaborators to publish

### ISSUE THREAD

**Issue by tilgovi** [remix/remix-jasmine-setup#3]
@janpaul123 would you add me as a collabor on NPM, please? @tilgovi there as well.

**Comment by janpaul123** [comment]
Oh, I stumbled upon this ticket by chance, since I didn't have watching enabled on this project. 😱 Next time feel free to send me a text / fb message if I don't respond. Anyway, added you on npm!

**Comment by tilgovi** [comment]
Thanks!
